name: Manual E2E Load Tests

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish.yml

  e2e-1GB-2-8:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "1000000000"
      oph_words: 2
      btree_order: 8

  e2e-10GB-2-8:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "10000000000"
      oph_words: 2
      btree_order: 8

  e2e-50GB-2-8:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "50000000000"
      oph_words: 2
      btree_order: 8