name: Manual E2E Load Tests

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish.yml

  e2e-1GB-4-16:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "1000000000"
      oph_words: 4
      btree_order: 16

  e2e-1GB-4-32:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "1000000000"
      oph_words: 4
      btree_order: 32

  e2e-10GB-4-16:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "10000000000"
      oph_words: 4
      btree_order: 16

  e2e-10GB-4-32:
    needs: publish
    uses: ./.github/workflows/e2e-bin.yml
    with:
      file_size: "10000000000"
      oph_words: 4
      btree_order: 32